const AUDIO_MAP = {
  "stitch selection dial": "audio/stitch selection dial (n).mp3",
  "needle presser dial": "audio/needle presser dial (n).mp3",
  "bobbin winder": "audio/bobbin winder (n).mp3",
  "upper tension control dial": "audio/upper tension control dial (n).mp3",
  "foot controller": "audio/foot controller (n).mp3",
  "thread take-up lever": "audio/thread take-up lever (n).mp3",
  "knee lifter": "audio/knee lifter (n).mp3",
  "bobbin": "audio/bobbin (n).mp3",
  "stitch length dial": "audio/stitch length dial (n).mp3",
  "hand wheel": "audio/hand wheel (n).mp3",
  "reverse stitch lever": "audio/reverse stitch lever (n).mp3",
  "needle clamp screw": "audio/needle clamp screw (n).mp3",
  "foot controller jack_socket": "audio/foot controller jack_socket (n).mp3",
  "presser foot": "audio/presser foot (n).mp3",
  "operation buttons.mp3": "audio/operation buttons.mp3",
  "presser foot holder": "audio/presser foot holder (n).mp3",
  "presser foot lever_lifter": "audio/presser foot lever_lifter (n).mp3",
  "operation panel": "audio/operation panel (n).mp3",
  "needle": "audio/needle (n).mp3",
  "feed dog": "audio/feed dog (n).mp3",
  "ship.mp3": "audio/ship.mp3",
  "payment terms.mp3": "audio/payment terms.mp3",
  "payment.mp3": "audio/payment.mp3",
  "quantity.mp3": "audio/quantity.mp3",
  "quality.mp3": "audio/quality.mp3",
  "goods.mp3": "audio/goods.mp3",
  "supply.mp3": "audio/supply.mp3",
  "delivery.mp3": "audio/delivery.mp3",
  "place an order.mp3": "audio/place an order.mp3",
  "purchase.mp3": "audio/purchase.mp3",
  "sample.mp3": "audio/sample.mp3",
  "catalogue.mp3": "audio/catalogue.mp3",
  "produce.mp3": "audio/Produce.mp3",
  "supplier.mp3": "audio/supplier.mp3",
  "manufacture.mp3": "audio/manufacture.mp3",
  "coral.mp3": "audio/Coral.mp3",
  "beige.mp3": "audio/Beige.mp3",
  "navy blue.mp3": "audio/Navy blue.mp3",
  "turquoise.mp3": "audio/Turquoise.mp3",
  "burgundy.mp3": "audio/Burgundy.mp3",
  "pastel.mp3": "audio/Pastel.mp3",
  "emerald.mp3": "audio/Emerald.mp3",
  "scarlet.mp3": "audio/Scarlet.mp3",
  "ash-gray.mp3": "audio/Ash-gray.mp3",
  "cuff.mp3": "audio/Cuff.mp3",
  "flap.mp3": "audio/Flap.mp3",
  "yoke.mp3": "audio/Yoke.mp3",
  "lapel.mp3": "audio/Lapel.mp3",
  "button.mp3": "audio/Button.mp3",
  "loop.mp3": "audio/Loop.mp3",
  "slit.mp3": "audio/Slit.mp3",
  "pocket.mp3": "audio/Pocket.mp3",
  "button placket.mp3": "audio/Button placket.mp3",
  "buttonhole.mp3": "audio/Buttonhole.mp3",
  "collar.mp3": "audio/Collar.mp3",
  "armhole.mp3": "audio/Armhole.mp3",
  "pad_shoulder pads.mp3": "audio/Pad_Shoulder pads.mp3",
  "crotch.mp3": "audio/Crotch.mp3",
  "ripped jeans.mp3": "audio/Ripped jeans.mp3",
  "jacket.mp3": "audio/Jacket.mp3",
  "baggy pants.mp3": "audio/Baggy pants.mp3",
  "skirt.mp3": "audio/Skirt.mp3",
  "skinny jeans.mp3": "audio/Skinny jeans.mp3",
  "pants.mp3": "audio/Pants.mp3",
  "coat.mp3": "audio/Coat.mp3",
  "jumper.mp3": "audio/Jumper.mp3",
  "t-shirt.mp3": "audio/T-shirt.mp3",
  "uniform.mp3": "audio/Uniform.mp3",
  "tie.mp3": "audio/Tie.mp3",
  "blouse.mp3": "audio/Blouse.mp3",
  "mittens.mp3": "audio/Mittens.mp3",
  "swimsuit.mp3": "audio/Swimsuit.mp3",
  "scarf.mp3": "audio/Scarf.mp3",
  "flip-flops.mp3": "audio/Flip-flops.mp3",
  "shorts.mp3": "audio/Shorts.mp3",
  "gloves.mp3": "audio/Gloves.mp3",
  "sweater.mp3": "audio/Sweater.mp3",
  "dress.mp3": "audio/Dress.mp3",
  "sneakers.mp3": "audio/Sneakers.mp3",
  "high heels.mp3": "audio/High heels.mp3",
  "suit.mp3": "audio/Suit.mp3",
  "shoes.mp3": "audio/Shoes.mp3",
  "cap.mp3": "audio/Cap.mp3",
  "boots.mp3": "audio/Boots.mp3",
  "trousers.mp3": "audio/Trousers.mp3",
  "sandals.mp3": "audio/Sandals.mp3",
  "jeans.mp3": "audio/Jeans.mp3",
  "shirt.mp3": "audio/Shirt.mp3",
  "trainers.mp3": "audio/Trainers.mp3",
  "tank top.mp3": "audio/Tank top.mp3",
  "bust_chest.mp3": "audio/Bust_Chest.mp3",
  "forearm.mp3": "audio/Forearm.mp3",
  "hip.mp3": "audio/Hip.mp3",
  "chin.mp3": "audio/Chin.mp3",
  "wrist.mp3": "audio/Wrist.mp3",
  "pelvis.mp3": "audio/Pelvis.mp3",
  "joint.mp3": "audio/Joint.mp3",
  "waist.mp3": "audio/Waist.mp3",
  "ankle.mp3": "audio/Ankle.mp3",
  "nape.mp3": "audio/Nape.mp3",
  "calf.mp3": "audio/Calf.mp3",
  "torso.mp3": "audio/Torso.mp3",
  "biceps.mp3": "audio/Biceps.mp3",
  "armpit.mp3": "audio/Armpit.mp3",
  "fit a garment on a model.mp3": "audio/Fit a garment on a model.mp3",
  "correct the pattern.mp3": "audio/Correct the pattern.mp3",
  "sew a prototype.mp3": "audio/Sew a prototype.mp3",
  "draft a preliminary pattern _ sketch your design.mp3": "audio/Draft a preliminary pattern _ Sketch your design.mp3",
  "drape the design.mp3": "audio/Drape the design.mp3",
  "lay out pattern pieces.mp3": "audio/Lay out pattern pieces.mp3",
  "cut a sample garment.mp3": "audio/Cut a sample garment.mp3",
  "pin.mp3": "audio/Pin.mp3",
  "steam iron.mp3": "audio/Steam iron.mp3",
  "ironing board.mp3": "audio/Ironing board.mp3",
  "tailor_s chalk.mp3": "audio/Tailor_s chalk.mp3",
  "colored pencil.mp3": "audio/Colored pencil.mp3",
  "water tank.mp3": "audio/Water tank.mp3",
  "thread.mp3": "audio/Thread.mp3",
  "measuring tape _ tape measure.mp3": "audio/Measuring tape _ Tape measure.mp3",
  "zipper.mp3": "audio/Zipper.mp3",
  "elastic band.mp3": "audio/Elastic band.mp3",
  "lace.mp3": "audio/Lace.mp3",
  "interlining.mp3": "audio/Interlining.mp3",
  "check _ plaid.mp3": "audio/Check _ Plaid.mp3",
  "stripe.mp3": "audio/Stripe.mp3",
  "velcro.mp3": "audio/Velcro.mp3",
  "pattern.mp3": "audio/Pattern.mp3",
  "label.mp3": "audio/Label.mp3",
  "accessory.mp3": "audio/Accessory.mp3",
  "ribbon.mp3": "audio/Ribbon.mp3",
  "twist.mp3": "audio/Twist.mp3",
  "finish.mp3": "audio/Finish.mp3",
  "work sth into sth.mp3": "audio/Work sth into sth.mp3",
  "print.mp3": "audio/Print.mp3",
  "sew.mp3": "audio/Sew.mp3",
  "pull.mp3": "audio/Pull.mp3",
  "cut.mp3": "audio/Cut.mp3",
  "inspect.mp3": "audio/Inspect.mp3",
  "weave.mp3": "audio/Weave.mp3",
  "harvest.mp3": "audio/Harvest.mp3",
  "comb.mp3": "audio/Comb.mp3",
  "pack.mp3": "audio/Pack.mp3",
  "bleach.mp3": "audio/Bleach.mp3",
  "knit.mp3": "audio/Knit.mp3",
  "gin.mp3": "audio/Gin.mp3",
  "separate.mp3": "audio/Separate.mp3",
  "spin.mp3": "audio/Spin.mp3",
  "dye.mp3": "audio/Dye.mp3",
  "press _ iron.mp3": "audio/Press _ Iron.mp3",
  "angle.mp3": "audio/Angle.mp3",
  "skeleton.mp3": "audio/Skeleton.mp3",
  "sketch.mp3": "audio/Sketch.mp3",
  "cylinder.mp3": "audio/Cylinder.mp3",
  "outline.mp3": "audio/Outline.mp3",
  "gesture drawing.mp3": "audio/Gesture drawing.mp3",
  "sketchbook.mp3": "audio/Sketchbook.mp3",
  "pose.mp3": "audio/Pose.mp3",
  "illustrate.mp3": "audio/Illustrate.mp3",
  "trend.mp3": "audio/Trend.mp3",
  "makeover.mp3": "audio/Makeover.mp3",
  "fashionable_ unfashionable.mp3": "audio/Fashionable_ unfashionable.mp3",
  "conservative.mp3": "audio/Conservative.mp3",
  "grunge.mp3": "audio/Grunge.mp3",
  "hip-hop fashion.mp3": "audio/Hip-hop fashion.mp3",
  "casual clothes.mp3": "audio/Casual clothes.mp3",
  "brand.mp3": "audio/Brand.mp3",
  "dramatic fashion.mp3": "audio/Dramatic fashion.mp3",
  "rayon.mp3": "audio/Rayon.mp3",
  "cotton cloth.mp3": "audio/Cotton cloth.mp3",
  "felt cloth.mp3": "audio/Felt cloth.mp3",
  "satin.mp3": "audio/Satin.mp3",
  "velvet.mp3": "audio/Velvet.mp3",
  "silk.mp3": "audio/Silk.mp3",
  "tweed .mp3": "audio/Tweed .mp3",
  "fleece": "audio/Fleece (fabric).mp3",
  "lace cloth.mp3": "audio/Lace cloth.mp3",
  "linen.mp3": "audio/Linen.mp3",
  "taffeta.mp3": "audio/Taffeta.mp3",
  "polyester.mp3": "audio/Polyester.mp3",
  "muslin.mp3": "audio/Muslin.mp3",
  "denim.mp3": "audio/Denim.mp3",
  "thread bunching _ nesting.mp3": "audio/Thread bunching _ Nesting.mp3",
  "bent needle.mp3": "audio/Bent needle.mp3",
  "needle breakage.mp3": "audio/Needle breakage.mp3",
  "fabric stagnant.mp3": "audio/Fabric stagnant.mp3",
  "skipped stitches.mp3": "audio/Skipped stitches.mp3",
  "thread breakage.mp3": "audio/Thread breakage.mp3",
  "blunt needle.mp3": "audio/Blunt needle.mp3",
  "loose stitches.mp3": "audio/Loose stitches.mp3",
  "uneven stitches.mp3": "audio/Uneven stitches.mp3",
  "machine jamming.mp3": "audio/Machine jamming.mp3",
  "fabric puckering.mp3": "audio/Fabric puckering.mp3",
  "noisy machine.mp3": "audio/Noisy machine.mp3",
  "self - assured": "audio/self - assured (adj).mp3",
  "rash": "audio/rash (adj).mp3",
  "negative": "audio/negative (adj).mp3",
  "angry stare": "audio/angry stare (np).mp3",
  "positive": "audio/positive (adj).mp3",
  "assertiveness": "audio/assertiveness (n).mp3",
  "make excuse": "audio/make excuse (vp).mp3",
  "negotiation": "audio/negotiation (n).mp3",
  "facial expression": "audio/facial expression (np).mp3",
  "scream": "audio/scream (v).mp3",
  "mumble": "audio/mumble (v).mp3",
  "face with": "audio/face with (vp).mp3",
  "body language": "audio/body language (np).mp3",
  "frown": "audio/frown (v).mp3",
  "hand gesture": "audio/hand gesture (np).mp3",
  "interact": "audio/interact (v).mp3",
  "non - verbal communication": "audio/non - verbal communication (np).mp3",
  "listening skill": "audio/listening skill (np).mp3",
  "interpersonal skills": "audio/interpersonal skills (np).mp3",
  "verbal communication": "audio/verbal communication (np).mp3",
  "individual.mp3": "audio/individual.mp3",
  "organizational environment": "audio/organizational environment (np).mp3",
  "communication": "audio/communication (n).mp3",
  "communicate with": "audio/communicate with (vp).mp3",
  "problem solving": "audio/problem solving (np).mp3",
  "effective": "audio/effective (adj).mp3",
  "ability": "audio/ability (n).mp3",
  "decision making": "audio/decision making (np).mp3",
  "ineffective": "audio/ineffective (adj).mp3",
  "change your mind": "audio/change your mind (vp).mp3",
  "analyzing option": "audio/analyzing option (np).mp3",
  "confirm.mp3": "audio/confirm.mp3",
  "remittance.mp3": "audio/remittance.mp3",
  "discount.mp3": "audio/discount.mp3",
  "inform.mp3": "audio/inform.mp3",
  "cancellation.mp3": "audio/cancellation.mp3",
  "cancel.mp3": "audio/cancel.mp3",
  "execute.mp3": "audio/execute.mp3",
  "charge.mp3": "audio/charge.mp3",
  "receipt.mp3": "audio/receipt.mp3",
  "information.mp3": "audio/information.mp3",
  "consider.mp3": "audio/consider.mp3",
  "arrival.mp3": "audio/arrival.mp3",
  "dispatch.mp3": "audio/dispatch.mp3",
  "arrive.mp3": "audio/arrive.mp3",
  "confirmation.mp3": "audio/confirmation.mp3",
  "execution.mp3": "audio/execution.mp3",
  "delay.mp3": "audio/delay.mp3",
  "refund.mp3": "audio/refund.mp3",
  "transfer.mp3": "audio/transfer.mp3",
  "consideration.mp3": "audio/consideration.mp3",
  "invoice.mp3": "audio/invoice.mp3",
  "deposit.mp3": "audio/deposit.mp3",
  "satisfaction.mp3": "audio/satisfaction.mp3",
  "term.mp3": "audio/term.mp3",
  "expense.mp3": "audio/expense.mp3",
  "(be) snug.mp3": "audio/(be) snug.mp3",
  "measure.mp3": "audio/measure.mp3",
  "measure around.mp3": "audio/measure around.mp3",
  "take measurements.mp3": "audio/take measurements.mp3",
  "back width.mp3": "audio/back width.mp3",
  "width.mp3": "audio/Width.mp3",
  "proportion.mp3": "audio/proportion.mp3",
  "side seam.mp3": "audio/side seam.mp3",
  "depth.mp3": "audio/depth.mp3",
  "fullest part.mp3": "audio/fullest part.mp3",
  "inch.mp3": "audio/Inch.mp3",
  "figure.mp3": "audio/Figure.mp3",
  "meter.mp3": "audio/meter.mp3",
  "horizontal.mp3": "audio/horizontal.mp3",
  "center front length.mp3": "audio/center front length.mp3",
  "front length.mp3": "audio/front length.mp3",
  "circumference.mp3": "audio/circumference.mp3",
  "(to) measure (from) waist to hip.mp3": "audio/(to) measure (from) waist to hip.mp3",
  "fit.mp3": "audio/Fit.mp3",
  "waistline.mp3": "audio/waistline.mp3",
  "centimeter.mp3": "audio/centimeter.mp3",
  "length.mp3": "audio/Length.mp3",
  "height.mp3": "audio/Height.mp3",
  "inseam.mp3": "audio/inseam.mp3",
  "distance.mp3": "audio/distance.mp3",
  "foot (singular) -_ feet": "audio/Foot (singular) -_ feet (plural).mp3",
  "vertical.mp3": "audio/vertical.mp3",
  "accurate.mp3": "audio/accurate.mp3",
  "attention": "audio/attention (n).mp3",
  "curious": "audio/curious (a).mp3",
  "follow-up question": "audio/follow-up question (np).mp3",
  "statement": "audio/statement (n).mp3",
  "auxiliary verb": "audio/auxiliary verb (n).mp3",
  "repeat": "audio/repeat (v).mp3",
  "technique": "audio/technique (n).mp3",
  "echo": "audio/echo (n).mp3",
  "repetition": "audio/repetition (n).mp3",
  "correct tense": "audio/correct tense (n).mp3",
  "encourage": "audio/encourage (v).mp3",
  "communication skills": "audio/communication skills (np).mp3",
  "ambition": "audio/ambition (n).mp3",
  "network": "audio/network (v).mp3",
  "common sense": "audio/common sense (np).mp3",
  "satisfaction": "audio/satisfaction (n).mp3",
  "issue": "audio/issue (n).mp3",
  "goal": "audio/goal (n).mp3",
  "(to) set oneself a goal": "audio/(to) set oneself a goal (v).mp3",
  "fulfill": "audio/fulfill (v).mp3",
  "market": "audio/market (v).mp3",
  "objective": "audio/objective (n).mp3",
  "incorporate": "audio/incorporate (v).mp3",
  "competency": "audio/competency (n).mp3",
  "consult": "audio/consult (v).mp3",
  "courtesy": "audio/courtesy (n).mp3",
  "initiate": "audio/initiate (v).mp3",
  "appreciate": "audio/appreciate (v).mp3",
  "target": "audio/target (n).mp3",
  "small talk": "audio/small talk (n).mp3",
  "deficiency": "audio/deficiency (n).mp3",
  "conflict": "audio/conflict (n).mp3",
  "transfer .mp3": "audio/transfer .mp3",
  "nurture": "audio/nurture (v).mp3",
  "workplace": "audio/workplace (n).mp3",
  "essential": "audio/essential (a).mp3",
  "co-worker": "audio/co-worker (n).mp3",
  "current affairs": "audio/current affairs (np).mp3",
  "progress": "audio/progress (v).mp3",
  "neglect": "audio/neglect (v).mp3",
  "commitment": "audio/commitment (n).mp3",
  "acquaintance": "audio/acquaintance (n).mp3",
  "cultivate": "audio/cultivate (v).mp3",
  "remove": "audio/remove (v).mp3",
  "clockwise": "audio/clockwise (v).mp3",
  "insert": "audio/insert (v).mp3",
  "lower": "audio/lower (v).mp3",
  "depress": "audio/depress (v).mp3",
  "press": "audio/press (v).mp3",
  "raise": "audio/raise (v).mp3",
  "place back into": "audio/place back into (v).mp3",
  "draw out": "audio/draw out (v).mp3",
  "take sth off sth": "audio/take sth off sth (v).mp3",
  "counterclockwise": "audio/counterclockwise (v).mp3",
  "examine": "audio/examine (v).mp3",
  "turn": "audio/turn (v).mp3",
  "lift": "audio/lift (v).mp3",
  "push_push up_push back": "audio/push_push up_push back (v).mp3"
};